### ISSUE TITLE
about video test

### ISSUE THREAD

**Issue by garycaocanxi** [bharatsubedi/ALPR-Yolov5#1]
Hi, sorry for I can not test my video, is this combine model is support video? I am looking forward your reply thank you.

**Comment by bharatsubedi** [comment]
@garycaocanxi you can use a combined model for video inferencing also but you have to change data loading. you can use OpenCV for loading video and convert it into frames then try inferencing. please try and let me know if you have any coding problems I will manage time and upload the full video inferencing file also.

**Comment by JFASOF** [comment]
Hello Bharat Subedi,
First of all, thank you for your project that you developed with Yolov5 and presented on github.
I need your support on the License Plate Recognition System. Is it possible to train our own model on synthetic data?

**Comment by bharatsubedi** [comment]
I hope you solved the video file handling problem. I will close this issue if you have still a problem reopen the issue again.
