### ISSUE TITLE
Detection accuracy is very poor

### ISSUE THREAD

**Issue by RifatSanaullah** [bharatsubedi/ALPR-Yolov5#11]
![image](https://user-images.githubusercontent.com/40433483/152293946-14ecff89-9fbc-43a8-bf79-199ec4a12fc1.png)
it can't detect far image, accuracy is not so good for far image or frame how can i improve it

**Comment by bharatsubedi** [comment]
If you want to detect a far image you should first localize your car image, crop car picture, and send it to this network for further process.

**Comment by RifatSanaullah** [comment]
> If you want to detect a far image you should first localize your car image, crop car picture, and send it to this network for further process.

what is the process if i want to pass video and detect from video frame??

**Comment by bharatsubedi** [comment]
you can use opencv for converting video into frames. 
but if you want to solve the problem of detection far image you should detect vehicle image first from scene image, crop vehicle image, and pass to my end-to-end pipeline.
