### ISSUE TITLE
Select chars to recognize

### ISSUE THREAD

**Issue by vswdigitall** [bharatsubedi/ALPR-Yolov5#13]
Hi, i tried and it works. Good work.
Can i select vocabulary? Only certain chars?

**Comment by bharatsubedi** [comment]
@vswdigitall yes you can. There are two ways to do
1) you can train the character detection model using your desired set of characters ( remove the other characters from the class name) and change the class name in the end-to-end VOC.yaml file. 
2) If this trained model is working fine and you don't need to finetune to your domain just use python code and keep only your desired character for output. 

I just create this repository public to help the community to understand how the ALPR system works for commercial purposes.

**Comment by vswdigitall** [comment]
Ok. Thank you.
