### ISSUE TITLE
Recognition of segmented characters from license plates

### ISSUE THREAD

**Issue by fadsamo** [bharatsubedi/ALPR-Yolov5#14]
Hello, I really thank you for what you did.
I need help implementing my own license plate recognition system.
I implemented plate detection using yolo and with the help of your codes and it works very well.
But for plate recognition(charcter recognition), my dataset includes characters separated from the license plate. That is, for each example of the numbers 0 to 9, I have about 1000 data, so I don't have the entire license plate.
In order to be able to implement this application, how should I label and use these codes to implement the plate recognition part?

![8 (10)](https://user-images.githubusercontent.com/31373251/179969929-4246b730-a016-43b7-b407-22045511d136.jpg)
![9 (13)](https://user-images.githubusercontent.com/31373251/179969993-1b55db5f-0711-45ae-8680-669a88fefb8b.jpg)
![Gh (11)](https://user-images.githubusercontent.com/31373251/179970025-3c97f2dc-379f-470c-9081-7a0159ec0758.jpg)

**Comment by fadsamo** [comment]
My question is, how should I first label these  character images (for example using the labelimg tool), and then use these images and their corresponding labels to identify the characters using your code?
And my second question is, after training the model using this data, can I give a license plate image and see the recognized characters in the output?
For example, the image below:

**Comment by WongVi** [comment]
@fadsamo 
You can use labelme tool and convert the data format to the coco yolo training format.
you can use any character, only you have to make labels correctly and train the network.
