### ISSUE TITLE
there is no recognition_best.pt file

### ISSUE THREAD

**Issue by PankajAS** [bharatsubedi/ALPR-Yolov5#15]
where i can find this file?

**Comment by bharatsubedi** [comment]
please check the redme file.
https://drive.google.com/file/d/1aNvYucWlfVy8w_Ijh0wEE9j7rtMCKLjR/view

**Comment by PankajAS** [comment]
Thanks @bharatsubedi

**Comment by PankajAS** [comment]
cap = cv2.VideoCapture('./video.mp4')
net = cv2.dnn.readNetFromONNX("./detection_best.onnx")
 
img = cv2.resize(img, (640,640))
blob = cv2.dnn.blobFromImage(img,scalefactor= 1/255,size=(640,640),mean=[0,0,0],swapRB= True, crop= False)

i'm using this with video to detect number plate but its throwing error
