### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'recognition_model/final_weights/recognition_best.pt'

### ISSUE THREAD

**Issue by elsonjose** [bharatsubedi/ALPR-Yolov5#3]
Change
`
weights_reco ='recognition_model/final_weights/recognition_best.pt'
`
to
`weights_reco ='recognition_model/final_weight/recognition_best.pt'`

in ALPR-Yolov5/end-t-end-test/combine_test.py

**Comment by bharatsubedi** [comment]
@elsonjose Thank you.
