### ISSUE TITLE
CPU Inference ?

### ISSUE THREAD

**Issue by Adeel-Intizar** [bharatsubedi/ALPR-Yolov5#5]
Hello, thank you for your amazing implementation 
How to use this implementation on CPU ? 
It'll be much appreciated if you help me with this,
Thank you

**Comment by bharatsubedi** [comment]
@Adeel-Intizar 
If you want to use CPU you have to use  `device= select_device('cpu')` during testing. you can check inside test.py or combine_test.py and change to CPU.
