### ISSUE TITLE
the combine code is not working

### ISSUE THREAD

**Issue by sekisek** [bharatsubedi/ALPR-Yolov5#6]
this line:
pred = model(img, augment=False)[0]

gives error:
'Hardswish' object has no attribute 'inplace'

probably because torch,torchvision versions.

can you fix it?

**Comment by sekisek** [comment]
Hi @bharatsubedi 

I did manage to work the weights in the yolov5 git ad it worked really nice!! thank you for that!

is there a way I can get a link to the image dataset + annotation that you used so  I can improve the accuracy with more images of my own?

**Comment by bharatsubedi** [comment]
I will not share annotation datasets. sorry
